import { type Node, type Edge } from '@xyflow/react';

// 出力したいJSONの型定義
type PipelineStep = {
    id: string;
    type: string;
    label: string;
    config: Record<string, any>;
    next_steps: string[]; // 接続先のIDリスト
};

type PipelineConfig = {
    version: string;
    generated_at: string;
    pipeline: PipelineStep[];
};

export const generatePipelineConfig = (nodes: Node[], edges: Edge[]): PipelineConfig => {
    // ノードごとに「次の接続先」を探しやすいようにマップ化
    // (エッジリストを走査して、source -> target の関係を整理)
    const adjacencyList: Record<string, string[]> = {};

    edges.forEach((edge) => {
        if (!adjacencyList[edge.source]) {
            adjacencyList[edge.source] = [];
        }
        adjacencyList[edge.source].push(edge.target);
    });

    // ノードを変換
    const steps: PipelineStep[] = nodes.map((node) => {
        // このノードから出ているエッジのターゲットIDを取得
        const nextNodeIds = adjacencyList[node.id] || [];

        return {
            id: node.id,
            type: node.data.type as string, // 'processing', 'trigger' など
            label: node.data.label as string,
            config: node.data.config as Record<string, any> || {},
            next_steps: nextNodeIds, // これで「つなぎ込み」が表現できる
        };
    });

    // 開始ノード（Trigger）が先頭に来るようにソートしてもいいですが、
    // 一旦はそのままリストとして返します
    return {
        version: "1.0.0",
        generated_at: new Date().toISOString(),
        pipeline: steps,
    };
};

// ...既存の generatePipelineConfig ...

// ★追加: Pythonコード生成関数
export const generatePythonCode = (nodes: any[], edges: any[]): string => {
    const config = generatePipelineConfig(nodes, edges);
    const steps = config.pipeline;

    let code = `# Generated by NeuroFlow Architect\n`;
    code += `# Date: ${new Date().toISOString()}\n\n`;
    code += `import os\n`;
    code += `from typing import Any, Dict\n\n`;
    code += `class NeuroPipeline:\n`;
    code += `    def __init__(self):\n`;
    code += `        print("Initializing pipeline...")\n`;

    // 各ノードの設定を __init__ に書き出す
    steps.forEach(step => {
        if (step.type === 'processing' && step.label.includes('LLM')) {
            code += `        self.llm = "ChatOpenAI(model='${step.config.model || 'gpt-4'}', temp=${step.config.temperature || 0.7})"\n`;
        }
        if (step.type === 'data') {
            code += `        self.vector_db = "Pinecone(index='${step.config.index || 'default'}')"\n`;
        }
    });

    code += `\n    def run(self, input_data: str) -> Dict[str, Any]:\n`;
    code += `        context = {}\n`;
    code += `        current_data = input_data\n\n`;

    // 実行フローを書き出す
    steps.forEach((step, index) => {
        code += `        # Step ${index + 1}: ${step.label} (${step.type})\n`;

        if (step.type === 'trigger') {
            code += `        print(f"🚀 Trigger: {current_data}")\n`;
        }
        else if (step.type === 'processing') {
            if (step.label.includes('Splitter')) {
                code += `        current_data = self._split_text(current_data, chunk_size=${step.config.chunkSize || 1000})\n`;
            } else if (step.label.includes('LLM')) {
                code += `        current_data = self._call_llm(current_data)\n`;
            } else {
                code += `        # Processing logic for ${step.label}...\n`;
            }
        }
        else if (step.type === 'data') {
            code += `        context['retrieved'] = self._search_db(current_data)\n`;
        }
        else if (step.type === 'action') {
            code += `        print(f"📧 Sending output: {current_data}")\n`;
        }

        code += `\n`;
    });

    code += `        return {"status": "success", "output": current_data}\n\n`;

    // ダミーのヘルパーメソッド
    code += `    def _split_text(self, text, chunk_size): return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]\n`;
    code += `    def _call_llm(self, prompt): return "LLM Response"\n`;
    code += `    def _search_db(self, query): return ["doc1", "doc2"]\n`;

    return code;
};